// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVphpcv45fU4nCuv9UZ5alLn8r8EUv9Ck',
    appId: '1:327102573982:web:cde86fb139ee6350293a8f',
    messagingSenderId: '327102573982',
    projectId: 'quizller-dcb83',
    authDomain: 'quizller-dcb83.firebaseapp.com',
    storageBucket: 'quizller-dcb83.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPWyT9-pgAVzIriYaqhFNkeB28BXzzLbw',
    appId: '1:327102573982:android:7f660fdb72e48e89293a8f',
    messagingSenderId: '327102573982',
    projectId: 'quizller-dcb83',
    storageBucket: 'quizller-dcb83.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCH-t86QSoqeHxrEUl-BpTU0U-m0QTWg5g',
    appId: '1:327102573982:ios:6ff98ef8c658830e293a8f',
    messagingSenderId: '327102573982',
    projectId: 'quizller-dcb83',
    storageBucket: 'quizller-dcb83.firebasestorage.app',
    iosBundleId: 'com.example.quizller',
  );

}